### ISSUE TITLE
Update workflow files for asdf action v1.1.0

### ISSUE THREAD

**Issue by smorimoto** [asdf-vm/asdf-plugin-template#17]
https://github.com/asdf-vm/actions/releases/tag/v1.1.0

**Comment by smorimoto** [comment]
CC: @jthegedus

**Comment by jthegedus** [comment]
The template references `@v1` which I understand pulls the latest minor.patch at the time the workflow runs, no?

https://github.com/asdf-vm/asdf-plugin-template/blob/8f51de0cc2ed8a663bf7d1628beb184eb9afe60d/template/.github/workflows/build.yml#L21

**Comment by smorimoto** [comment]
Yes, that's correct! But what I wanted to say is that we can remove the `env` field.

**Comment by jthegedus** [comment]
Ah yes, a good addition to the Actions :pray:
