### ISSUE TITLE
default github action for linting fails without adding a .tool-versions file to the plugin directory

### ISSUE THREAD

**Issue by comdotlinux** [asdf-vm/asdf-plugin-template#32]
**Describe the bug**
After Using the template to create the plugin repository, I noticed that without adding a .tool-versions file, the build fails

I had to add below to .tool-versions for the actions to run properly
```
nodejs 16.1.0
shfmt 3.2.4
```

**Steps to reproduce**

pick any tool, create the repository using the `use template` button and then push.

**Expected behavior**

If the Shellcheck and Shell Format are good then the action should pass

**Screenshots**

![image](https://user-images.githubusercontent.com/5428731/118263374-754d9b80-b4b6-11eb-9236-7a645657f92d.png)

**Additional context**

Look at https://github.com/comdotlinux/asdf-lazydocker/runs/2583308115?check_suite_focus=true for more details.
P.S. Ignore the commit message : I accidently used the same commit message as previous, this build has one entry in .tool-versions nodejs 16.1.0.

Also I had to create a `ASDF_DOWNLOAD_PATH="/tmp/${TOOL_NAME}"` variable in `lib/utils.bash` for the build to work.

**Comment by jthegedus** [comment]
>Also I had to create a ASDF_DOWNLOAD_PATH="/tmp/${TOOL_NAME}" variable in lib/utils.bash for the build to work.

This should be an optional env var :thinking: 

If someone sees this specific issue again, please open an new issue, thanks.
