### ISSUE TITLE
the `generate` script mentioned in the README.md is missing?

### ISSUE THREAD

**Issue by mcarifio** [asdf-vm/asdf-plugin-template#88]
The `generate` link in README.md is missing. I'm guessing it refers to a script to generate the content for the plugin instance. In any event, I'd prefer to start an asdf-plugin from some (debugged, sanctioned) template rather than copying an existing one (however good it might be). In the meantime, I'll review a few to grok the pattern(s).

Great tool, I use asdf all the time and would like to asdfify a tool whenever it's missing. For projects that release on github, I would think that's a pretty easy and mechanical process. After climbing the learning curve, of course.

**Comment by CanRau** [comment]
Are you referring to step 1. under usage?
I can just click and create a new repo based off it.
Here's the link jus tin case https://github.com/asdf-vm/asdf-plugin-template/generate
Other than that try the green button in the very top right saying `Use this template`

**Comment by mcarifio** [comment]
Huh. I stand corrected, ty. Hittin' the green button...
